---
# Install Nagios Clients.
- hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - nagios_client

# Install Nagios Server.
- hosts: nagios
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - nagios_server

